export const GAME_UPDATE_HIGH_SCORE = "GAME_UPDATE_HIGH_SCORE";
export const GAME_SET_TARGET = "GAME_SET_TARGET";
export const GAME_SET_REMAINING_TIME = "GAME_SET_REMAINING_TIME";
export const GAME_SET_LEVEL = "GAME_SET_LEVEL";
export const GAME_UPDGRADE_LEVEL = "GAME_UPDGRADE_LEVEL";
