export const GAME_UPDATE_HIGH_SCORE = "GAME_UPDATE_HIGH_SCORE";
export const GAME_SET_TARGET = "GAME_SET_TARGET";
export const GAME_SET_REMAINING_TIME = "GAME_SET_REMAINING_TIME";
export const GAME_SET_LEVEL = "GAME_SET_LEVEL";
export const GAME_UPDGRADE_LEVEL = "GAME_UPDGRADE_LEVEL";
export const GAME_TOOGLE_SOUND = "GAME_TOOGLE_SOUND";
export const GAME_SEE_PRESENTATION = "GAME_SEE_PRESENTATION";
